web:
  image: <ECR_URL>/devops-test
  tag: latest
  replicas: 1
  servicePort: 80

mysql:
  image: mysql:8
  db: targets
  user: targets
  password: password
  rootPassword: rootpassword
  storage: 5Gi

app:
  id: "1234"
